global using Xunit;
global using Application.Brew.Commands;
global using Common.Exceptions;
global using MediatR;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Moq;
global using ReadyTech.BrewCoffee.Api.Controllers;
global using ReadyTech.BrewCoffee.Api.Tests.Data;